name: Keep Alive Trigger

on:
  schedule:
    - cron: "0 0 */6 * *"
  workflow_dispatch:

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API keep-alive endpoint
        env:
          KEEP_ALIVE_TOKEN: ${{ secrets.KEEP_ALIVE_TOKEN }}
        run: |
          curl -X POST https://fragranciasapi.onrender.com/api/v1/keep-alive \
               -H "Content-Type: application/json" \
               -u "keep-alive:$KEEP_ALIVE_TOKEN"
